Task-3A: Please provide a similar table for your favorite 7 cities of Turkey that include their area and population.

In [1]:
import pandas as pd
#for year 2021
p_dict={"Eskişehir":898369,"Muğla":1021141,"İstanbul":15840900,"Giresun":450154,"Bursa":3147818,"Antalya":2619832,"Gaziantep":2130432,"Artvin":169543}
population=pd.Series(p_dict)
a_dict={"Eskişehir":13925,"Muğla":12655,"İstanbul":5461,"Giresun":6934,"Bursa":10882,"Antalya":20177,"Gaziantep":6803,"Artvin":7393}
area = pd.Series(a_dict)


data=pd.DataFrame({"Population": population,"Area": area})
data

           Population   Area
Eskişehir      898369  13925
Muğla         1021141  12655
İstanbul     15840900   5461
Giresun        450154   6934
Bursa         3147818  10882
Antalya       2619832  20177
Gaziantep     2130432   6803
Artvin         169543   7393